version: 2

sources:
  - name: source
    database: dbt_tutorial
    schema: source
    tables:
      - name: fact_sales_1
      - name: fact_returns
      - name: dim_store
      - name: dim_product
      - name: dim_customer
      - name: dim_date

      - name: items
